# Generated by Django 2.2.4 on 2019-09-07 11:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190907_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='user',
            name='enrollment_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='user',
            name='program',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sap_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='user',
            name='slots_occupied',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default='something', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_of_study', models.CharField(max_length=200)),
                ('slots_occupied', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_number', models.CharField(max_length=10)),
                ('sap_id', models.CharField(max_length=10)),
                ('program', models.CharField(max_length=100)),
                ('semester', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('cgpa', models.FloatField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
