# Generated by Django 2.2.4 on 2019-11-13 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCoordinator',
            fields=[
                ('Program', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('AC', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Teacher')),
            ],
        ),
    ]
