# Generated by Django 2.2.4 on 2019-09-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
    ]
