# Generated by Django 2.2.4 on 2019-11-03 10:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='students', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enrollment_number', models.CharField(max_length=10)),
                ('sap_id', models.CharField(max_length=10)),
                ('program', models.CharField(max_length=100)),
                ('semester', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('cgpa', models.FloatField(blank=True)),
                ('lock', models.IntegerField(default=0)),
                ('type_of_user', models.IntegerField(choices=[(0, 'Student')], default=0)),
            ],
            options={
                'permissions': [('manage_users', 'Can manage users')],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teachers', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='user-avatars')),
                ('field_of_study', models.CharField(max_length=200)),
                ('slots_occupied', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('department', models.CharField(max_length=200)),
                ('type_of_user', models.IntegerField(choices=[(1, 'HOD'), (2, 'AC'), (3, 'Professor')], default=3)),
            ],
            options={
                'permissions': [('manage_users', 'Can manage users'), ('manage_staff', 'Can manage staff')],
            },
        ),
    ]
