# Generated by Django 2.2.4 on 2019-09-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190915_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='type_of_user',
            field=models.IntegerField(choices=[('Student', 0), ('HOD', 1), ('AC', 2), ('Professor', 3)], default=3, max_length=1),
        ),
    ]
