# Generated by Django 2.2.4 on 2019-09-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190915_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='type_of_user',
            field=models.IntegerField(choices=[('Student', 0), ('HOD', 1), ('AC', 3), ('Professor', 3)], default=3),
        ),
    ]
