# Generated by Django 2.2.4 on 2019-09-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190915_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='type_of_user',
            field=models.IntegerField(choices=[('Student', 0)], default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='type_of_user',
            field=models.IntegerField(choices=[('HOD', 1), ('AC', 2), ('Professor', 3)], default=3),
        ),
    ]
