# Generated by Django 2.2.4 on 2019-09-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190915_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='type_of_user',
            field=models.IntegerField(choices=[(0, 'Student')], default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='type_of_user',
            field=models.IntegerField(choices=[(1, 'HOD'), (2, 'AC'), (3, 'Professor')], default=3),
        ),
    ]
