# Generated by Django 2.2.4 on 2019-11-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191030_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='lock',
            field=models.IntegerField(default=0),
        ),
    ]
