# Generated by Django 2.2.4 on 2019-09-22 09:34

import application.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.IntegerField(choices=[(0, 'Minor-I'), (1, 'Minor-II'), (2, 'Major-III'), (3, 'Major-IV'), (4, 'Other')], default=4)),
                ('title', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=500)),
                ('proposal', models.FileField(upload_to='proposals')),
                ('status', models.IntegerField(choices=[(0, 'Proposed'), (1, 'Accepted'), (2, 'Rejected')], default=0)),
                ('associated_files', models.FileField(blank=True, null=True, upload_to=application.models.Project.content_file_name)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='application.Project')),
            ],
        ),
    ]
