# Generated by Django 2.2.4 on 2019-11-03 10:12

import application.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.IntegerField(blank=True, choices=[(0, 'Minor-I'), (1, 'Minor-II'), (2, 'Major-III'), (3, 'Major-IV'), (4, 'Other')], default=4, null=True)),
                ('title', models.CharField(max_length=100)),
                ('abstract', models.CharField(blank=True, max_length=500, null=True)),
                ('proposal', models.FileField(upload_to='media/proposals')),
                ('associated_files', models.FileField(blank=True, null=True, upload_to=application.models.Project.content_file_name)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Proposed'), (1, 'Accepted'), (2, 'Rejected')], default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, to='accounts.Student')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Teacher')),
            ],
        ),
    ]
