# Generated by Django 2.2.4 on 2019-09-23 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190916_2044'),
        ('application', '0002_auto_20190923_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Teacher'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
