# Generated by Django 2.2.4 on 2019-09-25 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20190923_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abstract',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Teacher'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Minor-I'), (1, 'Minor-II'), (2, 'Major-III'), (3, 'Major-IV'), (4, 'Other')], default=4, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='proposal',
            field=models.FileField(blank=True, null=True, upload_to='proposals'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Proposed'), (1, 'Accepted'), (2, 'Rejected')], default=0, null=True),
        ),
    ]
