# Generated by Django 2.2.4 on 2019-10-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20191029_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proposal',
            field=models.FileField(default='abcd', upload_to='proposals'),
            preserve_default=False,
        ),
    ]
