# Generated by Django 2.2.4 on 2019-10-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20191031_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, to='accounts.Student'),
        ),
    ]
