# Generated by Django 2.2.4 on 2019-10-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20191031_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proposal',
            field=models.FileField(upload_to='storage/proposals'),
        ),
    ]
