# Generated by Django 2.2.4 on 2019-10-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20191031_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proposal',
            field=models.FileField(upload_to='media/proposals'),
        ),
    ]
