# Generated by Django 2.2.4 on 2019-11-04 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_student_lock'),
        ('application', '0012_auto_20191103_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='project',
            name='member1',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member1', to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='member2',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member2', to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='member3',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member3', to='accounts.Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='member4',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member4', to='accounts.Student'),
        ),
    ]
