# Generated by Django 2.2.4 on 2019-11-13 14:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='students', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('enrollment_number', models.CharField(max_length=10)),
                ('sap_id', models.CharField(max_length=10, unique=True)),
                ('semester', models.IntegerField(validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)])),
                ('CGPA', models.FloatField(blank=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('lock', models.IntegerField(default=0)),
                ('type_of_user', models.IntegerField(choices=[(0, 'Student')], default=0)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ActivityCoordinator')),
            ],
            options={
                'permissions': [('manage_users', 'Can manage users')],
            },
        ),
    ]
